=== paulooliva/paulooliva.github.io/papers/publications.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="papers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="paper" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string" />
                            <xs:element name="authors">
                                <xs:complexType mixed="true">
                                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                                        <xs:element name="a">
                                            <xs:complexType mixed="true">
                                                <xs:attribute name="href" use="required" />
                                                <xs:attribute name="target" use="optional" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="file_name" type="xs:string" />
                            <xs:element name="published" type="xs:string" />
                            <xs:element name="year" type="xs:string" />
                            <xs:element name="topic" type="xs:string" />
                            <xs:element name="extra" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="a">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="href" use="required" />
                                                        <xs:attribute name="target" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="comments" minOccurs="0" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== paulooliva/paulooliva.github.io/papers/publications.xml
<?xml version='1.0' encoding='UTF-8'?>
<papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="publications.xsd">

    <paper>
        <title>Convergence Rates for the Robbins-Monro Method via a Quantitative Analysis of
            Dvoretzky’s Theorem</title>
        <authors><a target="_blank" href="https://www.lemma-one.com/Arthan/homepage.html">Rob Arthan</a>
            and Paulo Oliva</authors>
        <file_name />
        <published>In preparation</published>
        <year>2026</year>
        <topic>Proof mining</topic>
    </paper>

    <paper>
        <title>A Systematic Way of Analysing Proofs in Probability Theory</title>
        <authors><a target="_blank" href="https://kejineri.github.io/">Morenikeji Neri</a>, Paulo
            Oliva and <a target="_blank" href="https://nicholaspischke.github.io/">Nicholas Pischke</a></authors>
        <file_name>https://arxiv.org/abs/2604.08078</file_name>
        <published>arXiv report (submitted)</published>
        <year>2026</year>
        <topic>Proof mining</topic>
    </paper>

    <paper>
        <title>Uniform Realizability Interpretations</title>
        <authors><a target="_blank" href="https://www.swansea.ac.uk/staff/u.berger/">Ulrich Berger</a>
            and Paulo Oliva</authors>
        <file_name>https://cgi.cse.unsw.edu.au/~eptcs/paper.cgi?LTT2026.3</file_name>
        <published>Electronic Proceedings in Theoretical Computer Science, 441, 46-61</published>
        <year>2026</year>
        <topic>Functional interpretations: Unifying functional interpretation</topic>
    </paper>

    <paper>
        <title>The Uniform Functional Interpretation with Informative Types</title>
        <authors><a target="_blank"
                href="https://www.acad-ciencias.pt/eng/scholars/fernando-ferreira/">Fernando
            Ferreira</a> and Paulo Oliva</authors>
        <file_name>https://arxiv.org/abs/2508.12781</file_name>
        <published>arXiv report (submitted for publication)</published>
        <year>2026</year>
        <topic>Functional interpretations: Unifying functional interpretation</topic>
    </paper>

    <paper>
        <title>Uniform Functional Interpretations</title>
        <authors>Paulo Oliva</authors>
        <file_name>https://dl.acm.org/doi/10.1007/978-3-031-95908-0_7</file_name>
        <published>Computability in Europe 2025, LNCS</published>
        <year>2025</year>
        <topic>Functional interpretations: Unifying functional interpretation</topic>
    </paper>

    <paper>
        <title>Higher-order Games with Dependent Types</title>
        <authors><a target="_blank" href="https://martinescardo.github.io/">Martín Escardó</a> and
            Paulo Oliva</authors>
        <file_name>https://www.sciencedirect.com/science/article/pii/S0304397523004243</file_name>
        <published>Theoretical Computer Science, vol 974</published>
        <year>2023</year>
        <topic>Game theory</topic>
    </paper>

    <paper>
        <title>On the Borel-Cantelli Lemmas, the Erdós-Rényi Theorem, and the Kochen-Stone Theorem</title>
        <authors><a target="_blank" href="https://www.lemma-one.com/Arthan/homepage.html">Rob Arthan</a>
            and Paulo Oliva</authors>
        <file_name>http://logicandanalysis.org/index.php/jla/article/view/412/178</file_name>
        <published>Journal of Logic and Analysis, 13:6, pages 1–23</published>
        <year>2021</year>
        <topic>Proof mining</topic>
    </paper>

    <paper>
        <title>Sorting and filtering as effective rational choice procedures</title>
        <authors>Paulo Oliva and Philipp Zahn</authors>
        <file_name>https://arxiv.org/pdf/1809.06766</file_name>
        <published>Unpublished report</published>
        <year>2021</year>
        <topic>Decision theory</topic>
    </paper>

    <paper>
        <title>On Rational Choice and the Representation of Decision Problems</title>
        <authors>Paulo Oliva and Philipp Zahn</authors>
        <file_name>https://www.mdpi.com/2073-4336/12/4/86</file_name>
        <published>Games, 12(4), 86</published>
        <year>2021</year>
        <topic>Decision theory</topic>
    </paper>

    <paper>
        <title>A parametrised functional interpretation of Heyting arithmetic</title>
        <authors><a target="_blank" href="https://scholar.google.com/citations?user=gDxotnMAAAAJ">Bruno
            Dinis</a> and Paulo Oliva</authors>
        <file_name>https://www.sciencedirect.com/science/article/abs/pii/S0168007220301640</file_name>
        <published>Annals of Pure and Applied Logic, 172:4</published>
        <year>2021</year>
        <topic>Functional interpretations: Unifying functional interpretation</topic>
    </paper>

    <paper>
        <title>Double Negation Semantics for Generalisations of Heyting Algebras</title>
        <authors><a target="_blank" href="https://www.lemma-one.com/Arthan/homepage.html">Rob Arthan</a>
            and Paulo Oliva</authors>
        <file_name>https://link.springer.com/article/10.1007/s11225-020-09909-y</file_name>
        <published>Studia Logica, vol 109, pages 341–365</published>
        <year>2021</year>
        <topic>Negative translations</topic>
    </paper>

    <paper>
        <title>On the Herbrand functional interpretation</title>
        <authors>Paulo Oliva and Chuangjie Xu</authors>
        <file_name>https://onlinelibrary.wiley.com/doi/abs/10.1002/malq.201900067?af=R</file_name>
        <published>Mathematical Logic Quarterly, 66:1, pages 91-98</published>
        <year>2020</year>
        <topic>Functional interpretations: Approximate functional interpretations</topic>
    </paper>

    <paper>
        <title>Kripke semantics for intuitionistic Lukasiewicz logic</title>
        <authors>Andrew Lewis, Paulo Oliva and <a target="_blank"
                href="https://www.qmul.ac.uk/eecs/people/profiles/robinsonedmund.html">Edmund
            Robinson</a></authors>
        <file_name>https://link.springer.com/article/10.1007/s11225-020-09908-z</file_name>
        <published>Studia Logica, vol 109, pages 313–339</published>
        <year>2020</year>
        <topic>Substructural logic</topic>
    </paper>

    <paper>
        <title>Studying algebraic structures using Prover9 and Mace4</title>
        <authors><a target="_blank" href="https://www.lemma-one.com/Arthan/homepage.html">Rob Arthan</a>
            and Paulo Oliva</authors>
        <file_name>https://www.springer.com/gp/book/9783030284824</file_name>
        <published>Proof Technology in Mathematics Research and Teaching, 91-111</published>
        <year>2019</year>
        <extra>
            <a href="/PTMRT/" target="_blank">Supporting material</a>
        </extra>
        <topic>Substructural logic</topic>
    </paper>

    <paper>
        <title>Negative translations for affine and Lukasiewicz logic</title>
        <authors><a target="_blank" href="https://www.lemma-one.com/Arthan/homepage.html">Rob Arthan</a>
            and Paulo Oliva</authors>
        <file_name>https://arxiv.org/abs/1912.00012</file_name>
        <published>arXiv report</published>
        <year>2019</year>
        <topic>Negative translations</topic>
    </paper>

    <paper>
        <title>A direct proof of Schwichtenberg's bar recursion closure theorem</title>
        <authors>Paulo Oliva and Silvia Steila</authors>
        <file_name>
            https://www.cambridge.org/core/journals/journal-of-symbolic-logic/article/direct-proof-of-schwichtenbergs-bar-recursion-closure-theorem/F22443746F35F8D74267925C69D2712E</file_name>
        <published>The Journal of Symbolic Logic, 83(1):70-83</published>
        <year>2018</year>
        <topic>Interpretations of Analysis: Bar recursion</topic>
    </paper>

    <paper>
        <title>A Curry-Howard correspondence for the minimal fragment Lukasiewicz logic</title>
        <authors><a target="_blank" href="https://www.lemma-one.com/Arthan/homepage.html">Rob Arthan</a>
            and Paulo Oliva</authors>
        <file_name>https://arxiv.org/abs/1809.04492</file_name>
        <published>arXiv report</published>
        <year>2018</year>
        <topic>Substructural logic</topic>
    </paper>

    <paper>
        <title>Higher-order decision theory</title>
        <authors><a target="_blank" href="https://julesh.com/">Jules Hedges</a>, Paulo Oliva,
            Evguenia Winschel, Viktor Winschel and Philipp Zahn</authors>
        <file_name>https://arxiv.org/abs/1506.01003</file_name>
        <published>Proceedings of the 5th International Conference on Algorithmic Decision Theory</published>
        <year>2017</year>
        <topic>Decision theory</topic>
    </paper>

    <paper>
        <title>Selection equilibria of higher-order games</title>
        <authors><a target="_blank" href="https://julesh.com/">Jules Hedges</a>, Paulo Oliva,
            Evguenia Winschel, Viktor Winschel and Philipp Zahn</authors>
        <file_name />
        <published>Nineteenth International Symposium on Practical Aspects of Declarative Languages</published>
        <year>2017</year>
        <topic>Game theory</topic>
    </paper>

    <paper>
        <title>The Herbrand functional interpretation of the double negation shift</title>
        <authors><a target="_blank" href="https://martinescardo.github.io/">Martín Escardó</a> and
            Paulo Oliva</authors>
        <file_name>
            https://www.cambridge.org/core/journals/journal-of-symbolic-logic/article/herbrand-functional-interpretation-of-the-double-negation-shift/21F52B85DDF053CA4839C2680906E1CD</file_name>
        <published>The Journal of Symbolic Logic</published>
        <year>2017</year>
        <topic>Interpretations of Analysis: Selection functions</topic>
    </paper>

    <paper>
        <title>Bar recursion over finite partial functions</title>
        <authors>Paulo Oliva and <a target="_blank" href="https://t-powell.github.io/">Thomas Powell</a></authors>
